### ISSUE TITLE
很失望

### ISSUE THREAD

**Issue by KINGFIOX** [ZhouZhaoJi/Library#1]
好好排版吧，一些代码块没高亮。还有一些错别字，还有一些把wait写成wiat，数不胜数。
别人老外可能会用一些诙谐的语言，你是觉得你翻译不通，然后还没把东西讲明白，你觉得很幽默吗？
你自己看看你写的是什么，我不想多说。
线程安全的栈，看你举了很多设想，最后我连实现都没看见，真垃圾。
读到第5章读不下去了。

**Comment by ZhouZhaoJi** [comment]
@KINGFIOX 我也觉得线程那本书翻译不好，不过我也不是翻译的人，我只是把书的pdf放这里，你是不是找错人了？

**Comment by KINGFIOX** [comment]
害，抱歉。想骂翻译作者，那翻译作者已经关闭issues了，哈哈哈。
